name: jupyter-graphql-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - gql
  - graphene
  - iso8601
  - jupyterlab >=0.35,<0.36
  - python >=3.6,<3.7
  - requests
  - werkzeug
  - pip:
    - graphql-ws
    - graphene-tornado
