#!/usr/bin/env bash
# This is used by repo2docker _after_ environment.yml, but still during the
# docker build, which is simpler than a dedicated Dockerfile
echo "CONDA_PREFIX is $CONDA_PREFIX"

JGQL_CLEANUP=0

if [ "${NB_UID}not-on-binder" = "not-on-binder" ]; then
  echo "...and that's fine"
else
  if [ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]; then
    echo "...and we set it to ${CONDA_DIR}"
    export CONDA_PREFIX=$CONDA_DIR
    export JGQL_CLEANUP=1
  else
    echo "...and that's fine"
  fi
fi

set -eux
python -m pip install -e . --ignore-installed --no-deps
python -m jupyter_graphql.fetch_static
jlpm bootstrap
jupyter labextension install --no-build $(cat labex.txt)
jupyter lab build
if [ "${JGQL_CLEANUP}" = "1" ]; then
  rm -rf $CONDA_PREFIX/share/jupyter/lab/staging
  jlpm cache clean
fi
